export BMLT_TEST_ROOT_SERVER=https://localhost:8889/_/sandwich
#export BMLT_TEST_ROOT_SERVER=https://na-bmlt.org/eccbc87e4b5ce2fe28308fd9f2a7baf3/bmltfed/main_server
echo "Test #1"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/json/?switcher=GetServerInfo"
echo "Test #2"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/serverInfo.xml"
echo "Test #3"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/xml/index.php?switcher=GetFormats"
echo "Test #4"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/xml/GetLangs.php"
echo "Test #5"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/xml/GetServiceBodies.php"
echo "Test #6"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/xsd/GetSearchResults.php"
echo "Test #7"
curl -g -k "${BMLT_TEST_ROOT_SERVER}/client_interface/json/?switcher=GetSearchResults&weekdays[]=1&weekdays[]=2&lat_val=35.542279819197&long_val=-78.64231134299&geo_width=-20"
echo "Test #8"
curl -k "${BMLT_TEST_ROOT_SERVER}"
echo "Test #9"
curl -k "${BMLT_TEST_ROOT_SERVER}/"
echo "Test #10"
curl -k "${BMLT_TEST_ROOT_SERVER}/filter?lat_val=35.5459732&long_val=-78.6398736"
echo "Test #11"
curl -k "${BMLT_TEST_ROOT_SERVER}/client_interface/json/?switcher=GetSearchResults&data_field_key=weekday_tinyint,start_time,service_body_bigint,id_bigint,meeting_name,location_text&sort_keys=meeting_name,service_body_bigint,weekday_tinyint,start_time"